remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "MIT Quantum Winter School 2026"
description: "Teaching a Quantum of Quantum Computing to undergraduate students in the Boston area. Instructors: Cora Barrett (MIT Physics), Om Joshi (MIT RLE), Ági Villányi (MIT CSAIL), Matthew Yeh (Harvard SEAS)."
